!/bin/bash

# set the WORDPRESS env vars from the bound ClearDB Service
export WORDPRESS_DB_USER=${VCAP_SERVICES_CLEARDB_0_CREDENTIALS_USERNAME}
export WORDPRESS_DB_PASSWORD=${VCAP_SERVICES_CLEARDB_0_CREDENTIALS_PASSWORD}
export WORDPRESS_DB_HOST=${VCAP_SERVICES_CLEARDB_0_CREDENTIALS_HOSTNAME}:${VCAP_SERVICES_CLEARDB_0_CREDENTIALS_PORT}
export WORDPRESS_DB_NAME=${VCAP_SERVICES_CLEARDB_0_CREDENTIALS_NAME}
